import type { DashboardState } from '../types/dashboard';

export const mockDashboardState: DashboardState = {
  project: {
    id: 'proj-123',
    name: 'SW Gainesville Land Analysis',
    type: 'developer_following',
    market: 'Gainesville, FL',
    marketCode: 'gainesville_fl',
    generatedAt: '2025-10-14T01:15:00Z',
    lastUpdated: '2025-10-14T03:20:00Z',
    isLive: true,
    updateCount: 7,
    confidence: 0.92,
    opportunities: 3,
  },
  latestUpdates: [
    {
      id: 'update-1',
      title: 'New acquisition detected',
      detail: 'D.R. Horton acquired parcel 13810-000-000 (0.38 acres) adjacent to Innovation Square.',
      timestamp: '2025-10-14T03:15:00Z',
      updateType: 'data_change',
      status: 'new',
      relatedProjectId: 'proj-123',
      changeType: 'acquisition',
      impact: 'positive',
    },
    {
      id: 'update-2',
      title: 'Opportunity added',
      detail: '12 vacant parcels under $100k identified within 1 mile of D.R. Horton cluster.',
      timestamp: '2025-10-14T02:45:00Z',
      updateType: 'new_opportunity',
      status: 'acknowledged',
      relatedProjectId: 'proj-123',
      changeType: 'new_opportunity',
    },
    {
      id: 'update-3',
      title: 'Market context refreshed',
      detail: 'Permit velocity up 18% month-over-month across Gainesville urban core.',
      timestamp: '2025-10-14T02:30:00Z',
      updateType: 'context',
      status: 'acknowledged',
      relatedProjectId: 'proj-123',
      changeType: 'market_shift',
    },
  ],
  trackingDensity: {
    label: 'Tracking density',
    value: '204 properties',
    metric: 'properties',
  },
  focusCard: {
    header: 'D.R. Horton Assemblage Activity',
    tag: 'High confidence',
    tagType: 'success',
    summary:
      'D.R. Horton invested $267M across 171 acquisitions in Gainesville since Jan 2025. Portfolio concentration in Innovation Square suggests near-term vertical development.',
    stats: [
      { label: 'Total properties', value: '204 (53% VACANT)' },
      { label: '2025 acquisitions', value: '171 ($267M)' },
      { label: 'Assemblage clusters', value: '4 active zones' },
    ],
  },
  markets: [
    {
      location: [29.6516, -82.3248],
      size: 0.18,
      label: 'Gainesville, FL',
      marketCode: 'gainesville_fl',
      properties: 204,
      entities: 89,
      activeEntities: 17,
      recentActivity: 'HIGH - D.R. Horton: 171 acquisitions in 2025',
      confidence: 0.88,
      confidenceLabel: 'High confidence',
    },
    {
      location: [29.6498, -82.3249],
      size: 0.06,
      label: 'Innovation Square Lot 7',
      marketCode: 'gainesville_fl',
      properties: 1,
      entities: 1,
      activeEntities: 1,
      recentActivity: 'Corner parcel inside Innovation Square overlay',
      confidence: 0.9,
      confidenceLabel: 'High',
      parcelId: '13810-000-000',
      propertyType: 'Vacant land',
      marketValue: 95000,
    },
    {
      location: [29.6487, -82.3262],
      size: 0.055,
      label: 'SW 4th Ave Gap Parcel',
      marketCode: 'gainesville_fl',
      properties: 1,
      entities: 1,
      activeEntities: 1,
      recentActivity: 'Completes Horton frontage on SW 4th Ave',
      confidence: 0.82,
      confidenceLabel: 'Medium',
      parcelId: '13811-000-000',
      propertyType: 'Vacant land',
      marketValue: 72000,
    },
    {
      location: [27.9506, -82.4572],
      size: 0.08,
      label: 'Tampa, FL',
      marketCode: 'tampa_fl',
      properties: 612,
      entities: 241,
      activeEntities: 36,
      recentActivity: 'Permit velocity spike: +37% MoM commercial permits',
      confidence: 0.62,
      confidenceLabel: 'Medium confidence',
    },
    {
      location: [30.3322, -81.6557],
      size: 0.06,
      label: 'Jacksonville, FL',
      marketCode: 'jacksonville_fl',
      properties: 488,
      entities: 203,
      activeEntities: 22,
      recentActivity: 'LLC cluster enrichment around logistics corridor',
      confidence: 0.34,
      confidenceLabel: 'Low confidence',
    },
  ],
  propertyDetails: {
    '13810-000-000': {
      parcelId: '13810-000-000',
      address: 'Innovation Square Lot 7',
      propertyType: 'Vacant land',
      zoning: 'MU-1',
      lotSizeSqft: 16500,
      acreage: 0.38,
      marketValue: 95000,
      assessedValue: 91000,
      owner: 'D R HORTON INC',
      ownerType: 'corporate',
      lastSaleDate: '2025-08-12',
      lastSalePrice: 87000,
      confidence: 0.9,
      aiSummary: 'Corner parcel within Innovation Square overlay ready for vertical development.',
      highlights: [
        'Inside Innovation Square redevelopment district',
        'Utilities stubbed at lot line',
        'Eligible for MU-1 mixed-use entitlements',
      ],
    },
    '13811-000-000': {
      parcelId: '13811-000-000',
      address: 'SW 4th Ave Gap Parcel',
      propertyType: 'Vacant land',
      zoning: 'MU-1',
      lotSizeSqft: 12100,
      acreage: 0.28,
      marketValue: 72000,
      assessedValue: 68500,
      owner: 'Innovation Square Holdings LLC',
      ownerType: 'llc',
      lastSaleDate: '2024-11-02',
      lastSalePrice: 59000,
      confidence: 0.82,
      aiSummary: 'Gap parcel completing east-west frontage for Horton assemblage.',
      highlights: [
        'Completes Horton frontage on SW 4th Ave',
        'Level site with existing curb cuts',
      ],
    },
  },
  reportContent: {
    projectId: 'proj-123',
    projectName: 'SW Gainesville Land Analysis',
    analysisType: 'Entity tracking analysis',
    confidence: 0.92,
    confidenceLabel: 'High confidence',
    dataCoverage: '2021-2025 (204 properties)',
    summary:
      'Dominion analyzed D.R. Horton\'s Gainesville portfolio, identifying accelerated assemblage around Innovation Square with supporting signals from permits, parcel acquisitions, and council agendas. Vacant parcel inventory and price velocity confirm a near-term vertical development window.',
    sections: [
      {
        title: 'Portfolio Breakdown',
        content:
          'Dominion tracked 204 Gainesville properties belonging to D.R. Horton, 53% of which are vacant parcels positioned inside Innovation Square and SW Gainesville. Assemblage activity increased 31% over the last 90 days.',
        metrics: [
          { label: 'Total properties', value: '204 ($6.96M)', highlight: true },
          { label: 'VACANT land', value: '106 (53%)' },
          { label: 'SINGLE FAMILY', value: '98 (47%)' },
        ],
      },
      {
        title: 'Acquisition Velocity',
        content:
          '171 acquisitions closed in 2025 with the majority executed through single-purpose LLCs. Dominion traced shell entities back to D.R. Horton via Sunbiz officer alignment.',
        metrics: [
          { label: '2025 acquisitions', value: '171', highlight: true },
          { label: 'Average lead time', value: '12 days' },
          { label: 'Capital deployed', value: '$267M' },
        ],
      },
      {
        title: 'Market Context',
        content:
          'Permit velocity rose 18% month-over-month and Gainesville council minutes reference Innovation Square redevelopment requests filed by D.R. Horton partners. Competing developers remain supply constrained.',
      },
    ],
    nextActions: [
      'Map all 106 vacant parcels to identify assemblage clusters.',
      'Find gap parcels within acquisition zones to assign or wholesale.',
      'Monitor Innovation Square council agenda for zoning adjustments.',
    ],
    sources: {
      tools: ['analyze_entity', 'get_entity_properties', 'analyze_location'],
      databases: ['bulk_property_records', 'entities'],
      coverage: '108,380 properties, 89,189 entities',
    },
  },
  opportunityQueue: [
    {
      id: 'opp-1',
      type: 'entity_following',
      entity: 'D R HORTON INC',
      market: 'Gainesville, FL',
      marketCode: 'gainesville_fl',
      signal: '171 acquisitions in 2025 ($267M invested)',
      signalType: 'acquisition_velocity',
      confidence: 0.92,
      confidenceLabel: 'High confidence',
      leadTime: 'IMMEDIATE',
      action: 'Find gap parcels near their activity',
      estimatedReturn: '15-25% (wholesale to developer)',
      status: 'new',
      risks: ['Market timing', 'Strategy change'],
      supportingTools: ['analyze_entity', 'get_entity_properties'],
      relatedProjectId: 'proj-123',
      discoveredAt: '2025-10-14T01:17:00Z',
    },
    {
      id: 'opp-2',
      type: 'assemblage',
      market: 'Gainesville, FL',
      marketCode: 'gainesville_fl',
      signal: '12 VACANT parcels under $100k within 1 mile of D.R. Horton cluster',
      signalType: 'clustering',
      confidence: 0.85,
      confidenceLabel: 'High confidence',
      leadTime: '45-60d',
      action: 'Wholesale gap parcels to D.R. Horton or co-develop',
      estimatedReturn: '15-20% (wholesale)',
      status: 'queued',
      risks: ['Seller engagement', 'Entitlement timing'],
      supportingTools: ['search_properties', 'analyze_location'],
      relatedProjectId: 'proj-123',
      discoveredAt: '2025-10-14T01:18:00Z',
    },
    {
      id: 'opp-3',
      type: 'property_deal',
      property: 'Innovation Square Lot 7',
      market: 'Gainesville, FL',
      marketCode: 'gainesville_fl',
      signal: 'Undervalued parcel adjacent to D.R. Horton holdings',
      signalType: 'price_gap',
      confidence: 0.78,
      confidenceLabel: 'Good confidence',
      leadTime: '30d',
      action: 'Acquire at assessed value for immediate equity',
      estimatedReturn: '8-10% instant equity',
      status: 'in_analysis',
      supportingTools: ['analyze_comparable_sales', 'analyze_property'],
      relatedProjectId: 'proj-123',
      discoveredAt: '2025-10-14T01:19:00Z',
    },
  ],
  activityLog: [
    {
      id: 'step-1',
      timestamp: '2025-10-14T01:15:32Z',
      toolName: 'analyze_entity',
      description: 'Analyzing D R HORTON INC portfolio',
      result: 'Found 204 properties ($6.96M total value)',
      status: 'complete',
      duration: '1.2s',
    },
    {
      id: 'step-2',
      timestamp: '2025-10-14T01:15:45Z',
      toolName: 'get_entity_properties',
      description: 'Retrieving property list',
      result: 'Retrieved 106 VACANT land parcels',
      status: 'complete',
      duration: '0.8s',
    },
    {
      id: 'step-3',
      timestamp: '2025-10-14T01:16:02Z',
      toolName: 'analyze_location',
      description: 'Searching for nearby properties',
      result: 'Found 87 properties within 1 mile, 12 VACANT parcels under $100k',
      status: 'complete',
      duration: '2.1s',
    },
    {
      id: 'step-4',
      timestamp: '2025-10-14T01:16:18Z',
      toolName: 'analyze_market',
      description: 'Running market analysis',
      result: 'Gainesville market shows 13 active buyers',
      status: 'complete',
      duration: '1.5s',
    },
    {
      id: 'step-5',
      timestamp: '2025-10-14T01:16:35Z',
      toolName: 'search_properties',
      description: 'Filtering for VACANT land under $50k',
      result: 'Found 10 matching properties',
      status: 'complete',
      duration: '0.9s',
    },
  ],
  isLive: true,
  lastDataCheck: '2025-10-14T03:20:00Z',
};
