import type { ProjectSummary } from '../types/dashboard';

export const mockProjects: ProjectSummary[] = [
  {
    id: 'proj-123',
    name: 'SW Gainesville Land Analysis',
    type: 'developer_following',
    market: 'Gainesville, FL',
    marketCode: 'gainesville_fl',
    status: 'live',
    progress: 100,
    createdAt: '2025-10-10T14:20:00Z',
    lastUpdated: '2025-10-14T03:20:00Z',
    description: 'Following D.R. Horton portfolio moves and assemblage patterns across Innovation Square.',
    confidence: 0.92,
    opportunities: 3,
  },
  {
    id: 'proj-231',
    name: 'Tampa River District Permit Surge',
    type: 'market_research',
    market: 'Tampa, FL',
    marketCode: 'tampa_fl',
    status: 'complete',
    progress: 100,
    createdAt: '2025-10-09T09:05:00Z',
    lastUpdated: '2025-10-13T18:44:00Z',
    description: 'Quantifying commercial permit velocity and identifying priority contractors for outreach.',
    confidence: 0.88,
    opportunities: 2,
  },
  {
    id: 'proj-312',
    name: 'Innovation Square Gap Parcels',
    type: 'assemblage_investigation',
    market: 'Gainesville, FL',
    marketCode: 'gainesville_fl',
    status: 'generating',
    progress: 68,
    createdAt: '2025-10-14T01:42:00Z',
    lastUpdated: '2025-10-14T02:11:00Z',
    description: 'Locating assignable parcels within D.R. Horton acquisition zones for wholesale positioning.',
    confidence: 0.76,
    opportunities: 1,
  },
  {
    id: 'proj-404',
    name: 'Jacksonville Logistics Dossier',
    type: 'developer_following',
    market: 'Jacksonville, FL',
    marketCode: 'jacksonville_fl',
    status: 'complete',
    progress: 100,
    createdAt: '2025-10-05T12:30:00Z',
    lastUpdated: '2025-10-12T16:05:00Z',
    description: 'Entity enrichment and property aggregation for logistics corridor repeat buyers.',
    confidence: 0.84,
    opportunities: 4,
  },
  {
    id: 'proj-518',
    name: 'Miami Value-Add Condo Review',
    type: 'price_validation',
    market: 'Miami, FL',
    marketCode: 'miami_fl',
    status: 'draft',
    progress: 12,
    createdAt: '2025-10-14T14:05:00Z',
    lastUpdated: '2025-10-14T14:05:00Z',
    description: 'Validating pricing assumptions on urban infill condo conversion candidates.',
    confidence: undefined,
    opportunities: 0,
  },
  {
    id: 'proj-602',
    name: 'Orlando Infill Opportunity Sweep',
    type: 'market_research',
    market: 'Orlando, FL',
    marketCode: 'orlando_fl',
    status: 'complete',
    progress: 100,
    createdAt: '2025-09-28T08:10:00Z',
    lastUpdated: '2025-10-11T10:52:00Z',
    description: 'Surveying sub-$1.5M infill parcels near SunRail expansion for quick-turn developments.',
    confidence: 0.81,
    opportunities: 5,
  },
];
