# Docker Compose for CitizenServe Scraper
# Production deployment configuration for Oracle VPS

version: '3.8'

services:
  citizenserve-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dominion-citizenserve-scraper
    restart: unless-stopped
    init: true
    ipc: host
    shm_size: 1gb

    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - DOWNLOAD_DIR=/app/downloads
      - HEADLESS=false
      - DISPLAY=:99

    # Volume mounts
    volumes:
      - ./downloads:/app/downloads:rw  # Persistent download storage
      - ./logs:/app/logs:rw           # Persistent logs
      - /etc/localtime:/etc/localtime:ro  # Use host timezone

    # Resource limits (adjust based on VPS capacity)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

    # Network security
    networks:
      - scraper-network

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.append('BypassV3'); from bypass import ReCaptchaV3Bypass; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Security options
    security_opt:
      - no-new-privileges:true

    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  # Optional: Add Redis for job scheduling (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   container_name: dominion-redis
  #   restart: unless-stopped
  #   networks:
  #     - scraper-network
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
  #         cpus: '0.25'

networks:
  scraper-network:
    driver: bridge
    internal: false  # Allow internet access for scraping

volumes:
  downloads:
    driver: local
  logs:
    driver: local